title: Lies Incorporated
description: ... but the computer, being programmed to lie, would of course lie --  even to Lies Incorporated itself.
google_analytics:
show_downloads: false
theme: jekyll-theme-cayman

gems:
  - jekyll-mentions
